title: "Резюме Kitsune Solar"
description: "Системный администратор и веб-разработчик"
image: ""
lang: "ru_RU"

defaults:
  - scope:
      path: ""
    values:
      image: ""

author:
  name: "Kitsune Solar"
  email: "kitsune.solar@gmail.com"
  github: "KitsuneSolar"
  twitter: "KitsuneSolar"

twitter:
  username: "KitsuneSolar"
  card: summary

social:
  name: "Kitsune Solar"
  links:
    - https://kitsune.solar
    - https://facebook.com/KitsuneSolar
    - https://github.com/KitsuneSolar
    - https://gitlab.com/KitsuneSolar
    - https://instagram.com/KitsuneSolar
    - https://linkedin.com/in/KitsuneSolar
    - https://t.me/KitsuneSolar
    - https://twitch.tv/KitsuneSolar
    - https://twitter.com/KitsuneSolar
    - https://vk.com/KitsuneSolar
    - https://youtube.com/KitsuneSolar

webmaster_verifications:
  google: ""
  yandex: ""

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
